# Generated by Django 3.1.4 on 2020-12-10 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, choices=[('Chem', 'Chem'), ('Gluten', 'Gluten'), ('Soap', 'Soap')], null=True, size=20),
        ),
    ]
