# Generated by Django 3.1.4 on 2020-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201207_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_clinic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Clinic', 'Clinic')], default='Patient', max_length=32),
        ),
    ]
