# Generated by Django 3.1.4 on 2020-12-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201211_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
