# Generated by Django 3.1.4 on 2020-12-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
