# Generated by Django 3.1.4 on 2020-12-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
