# Generated by Django 3.1.4 on 2020-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201209_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='area',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Vet', 'Vet'), ('Dentist', 'Dentist')], max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
