# Generated by Django 3.1.4 on 2021-01-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201219_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('state_id', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timezone', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
