# Generated by Django 3.1.6 on 2021-03-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_clinic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
