# Generated by Django 3.1.4 on 2020-12-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20201216_1957'),
        ('clinics', '0002_auto_20201218_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='clinics', to='doctors.Doctor'),
        ),
    ]
