# Generated by Django 3.1.4 on 2021-02-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_auto_20210125_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='city',
        ),
    ]
