# Generated by Django 3.1.4 on 2021-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctors',
        ),
    ]
