# Generated by Django 3.1.4 on 2021-02-04 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0009_remove_clinic_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='user',
        ),
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff_clinics', to=settings.AUTH_USER_MODEL),
        ),
    ]
