# Generated by Django 3.1.4 on 2021-02-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_auto_20210204_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
