# Generated by Django 3.1.6 on 2021-03-12 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0013_auto_20210212_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='allowed_raters',
            field=models.ManyToManyField(blank=True, related_name='clinic_rates', to=settings.AUTH_USER_MODEL),
        ),
    ]
