# Generated by Django 3.1.2 on 2020-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trade_number',
            field=models.IntegerField(blank=True),
        ),
    ]
