# Generated by Django 3.1.2 on 2020-12-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20201204_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
    ]
