# Generated by Django 3.1.2 on 2020-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_number',
            field=models.IntegerField(default=9999999999),
        ),
    ]
