# Generated by Django 3.1.2 on 2020-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20201204_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_number',
            field=models.CharField(default='99999999999', max_length=20),
        ),
    ]
