# Generated by Django 3.1.2 on 2020-12-04 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20201204_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
