# Generated by Django 3.1.2 on 2020-12-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20201206_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
