# Generated by Django 3.1.4 on 2021-01-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210120_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
    ]
