# Generated by Django 3.1.6 on 2021-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_notification_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='clinic',
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
