# Generated by Django 3.1.6 on 2021-03-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_auto_20210212_2257'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0033_delete_rate'),
        ('base', '0008_auto_20210224_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('is_doctor_rating', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=280)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=models.Model, related_name='ratings', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='doctors.doctor')),
                ('user', models.ManyToManyField(related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
