# Generated by Django 3.1.6 on 2021-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210302_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
