# Generated by Django 3.1.4 on 2021-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_allergy_condition_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_conditions',
        ),
        migrations.AddField(
            model_name='patient',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='people', to='patients.Condition'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='users', to='patients.Medication'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='allergic', to='patients.Allergy'),
        ),
    ]
