# Generated by Django 3.1.4 on 2021-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210128_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='allergy',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication',
            field=models.CharField(max_length=128),
        ),
    ]
