# Generated by Django 3.1.4 on 2021-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='areas',
        ),
        migrations.AddField(
            model_name='doctor',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.Service'),
        ),
    ]
