# Generated by Django 3.1.4 on 2021-01-25 22:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20210125_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='areas',
        ),
        migrations.AddField(
            model_name='doctor',
            name='areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
