# Generated by Django 3.1.4 on 2021-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20210128_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.Area'),
        ),
    ]
