# Generated by Django 3.1.4 on 2021-02-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_day'),
        ('clinics', '0009_remove_clinic_doctors'),
        ('doctors', '0009_auto_20210128_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='clinics.Clinic'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('break_time', models.TimeField(blank=True, null=True)),
                ('area', models.ManyToManyField(blank=True, related_name='shifts', to='doctors.Area')),
                ('clinic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='clinics.clinic')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='users.day')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='doctors.doctor')),
            ],
        ),
    ]
