# Generated by Django 3.1.4 on 2021-02-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_auto_20210201_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='area',
            new_name='areas',
        ),
    ]
