# Generated by Django 3.1.4 on 2021-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_shift_break_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
