# Generated by Django 3.1.4 on 2021-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_shift_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
