# Generated by Django 3.1.4 on 2021-02-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='index',
        ),
    ]
