# Generated by Django 3.1.4 on 2021-02-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_remove_appointment_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
