# Generated by Django 3.1.4 on 2021-02-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_auto_20210209_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.area'),
        ),
    ]
