# Generated by Django 3.1.4 on 2021-02-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_auto_20210209_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='areas_search',
            field=models.CharField(blank=True, max_length=528, null=True),
        ),
    ]
