# Generated by Django 3.1.4 on 2021-02-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_doctor_areas_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='areas_search',
        ),
    ]
