# Generated by Django 3.1.6 on 2021-02-14 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0013_auto_20210212_2257'),
        ('doctors', '0022_remove_doctor_areas_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('clinic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('user', models.ManyToManyField(blank=True, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
