# Generated by Django 3.1.6 on 2021-02-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user',
            new_name='users',
        ),
    ]
