# Generated by Django 3.1.6 on 2021-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0024_auto_20210215_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='picture',
            field=models.ImageField(default='area-default.png', upload_to=''),
        ),
    ]
