# Generated by Django 3.1.6 on 2021-02-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_auto_20210223_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='symbol',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
