# Generated by Django 3.1.6 on 2021-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0028_auto_20210224_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
