# Generated by Django 3.1.6 on 2021-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0029_appointment_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='picture',
            field=models.ImageField(default='general-practice_ApZO4A.png', upload_to=''),
        ),
    ]
