# Generated by Django 3.1.6 on 2021-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0032_auto_20210301_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
