# Generated by Django 3.1.6 on 2021-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0033_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
