# Generated by Django 3.1.6 on 2021-03-12 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0034_appointment_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='allowed_raters',
            field=models.ManyToManyField(blank=True, related_name='raters', to=settings.AUTH_USER_MODEL),
        ),
    ]
