name: Testing
on: push

jobs:
        test-project:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: | 
                                pip3 install --user django
                                python3 manage.py test 
