name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        pip3 install -U setuptools
        pip3 install psycopg2-binary
        pip3 install -r requirements.txt
        sudo apt-get install python3.9
        python3 manage.py test
        
